const NOT_FOUND_ERROR_MESSAGE = 'Ресурс не найден';
const NOT_FOUND_CODE = 404;
const BAD_REQUEST_ERROR_MESSAGE = 'Неверный формат данных';
const BAD_REQUEST_CODE = 400;
const FORBIDDEN_MOVIES_ERROR_MESSAGE = 'Нельзя удалить фильм';
const FORBIDDEN_CODE = 403;
const CONFLICT_USERS_ERROR_MESSAGE = 'Пользователь с данным email уже существует';
const CONFLICT_CODE = 409;
const UNAUTHORIZED_ERROR_MESSAGE = 'Необходима авторизация';
const UNAUTHORIZED_CODE = 401;

module.exports = {
  NOT_FOUND_ERROR_MESSAGE,
  NOT_FOUND_CODE,
  BAD_REQUEST_ERROR_MESSAGE,
  BAD_REQUEST_CODE,
  FORBIDDEN_MOVIES_ERROR_MESSAGE,
  FORBIDDEN_CODE,
  CONFLICT_USERS_ERROR_MESSAGE,
  CONFLICT_CODE,
  UNAUTHORIZED_CODE,
  UNAUTHORIZED_ERROR_MESSAGE,
};
